version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-test
    environment:
      MARIADB_DATABASE: test
      MARIADB_USER: root
      MARIADB_PASSWORD: 12345
      MARIADB_ROOT_PASSWORD: 12345
    ports:
      - "3307:3306"
